server:
  port: 10002
dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848
  cloud:
    subscribed-services: dubbo-springboot-micrometer-server

nacos:
  discovery:
    register:
      healthy: false
    server-addr: localhost:8848

spring:
  application:
    name: dubbo-consumer