server:
  port: 10001
spring:
  application:
    name: dubbo-springboot-micrometer-server
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
dubbo:
  scan:
    base-packages: com.coder4.dsm.server.service.impl
  protocol:
    name: dubbo
    port: -1
  registry:
    address: spring-cloud://localhost