server:
  port: 10001

spring:
  application:
    name: dubbo-springboot-micrometer-server

nacos:
  discovery:
    register:
      healthy: false
    server-addr: localhost:8848

dubbo:
  scan:
    base-packages: com.coder4.dsm.server.service.impl
  protocol:
    name: dubbo
    port: -1
  registry:
    address: nacos://localhost:8848